provisioning:
  - changed-files:
      - any-glob-to-any-file:
          - provision/orchestrate.sh
          - provision/orchestrate-terminal.sh
          - provision/orchestrate-desktop.sh
          - bootstrap.sh
core:
  - changed-files:
      - any-glob-to-any-file:
          - provision/core/**
terminal tools:
  - changed-files:
      - any-glob-to-any-file:
          - provision/terminal/**
desktop tools:
  - changed-files:
      - any-glob-to-any-file:
          - provision/desktop/**
extensions:
  - changed-files:
      - any-glob-to-any-file:
          - provision/desktop/extensions/**
shared assets:
  - changed-files:
      - any-glob-to-any-file:
          - share/**
shell configuration:
  - changed-files:
      - any-glob-to-any-file:
          - shell/**
          - config/**
cli management:
  - changed-files:
      - any-glob-to-any-file:
          - bin/**
revert:
  - changed-files:
      - any-glob-to-any-file:
          - revert/**
documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
github config:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**
